// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatContent: typeof import('./src/components/chat/chatPanel/chatContent.vue')['default']
    ChatInput: typeof import('./src/components/chat/chatPanel/chatInput.vue')['default']
    ChatList: typeof import('./src/components/chat/chatList/chatList.vue')['default']
    ChatPanel: typeof import('./src/components/chat/chatPanel/chatPanel.vue')['default']
    ChatPanelBar: typeof import('./src/components/chat/chatPanel/chatPanelBar.vue')['default']
    ContactItem: typeof import('./src/components/contact/contactList/contactItem.vue')['default']
    ContactList: typeof import('./src/components/contact/contactList/contactList.vue')['default']
    ContactPanel: typeof import('./src/components/contact/contactPanel/contactPanel.vue')['default']
    FriendInfo: typeof import('./src/components/contact/contactPanel/friendInfo.vue')['default']
    FriendList: typeof import('./src/components/contact/contactList/friendList.vue')['default']
    GroupInfo: typeof import('./src/components/contact/contactPanel/groupInfo.vue')['default']
    GroupList: typeof import('./src/components/contact/contactList/groupList.vue')['default']
    HomeContent: typeof import('./src/components/home/homeContent.vue')['default']
    HomeFooter: typeof import('./src/components/home/homeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/home/homeHeader.vue')['default']
    ListItem: typeof import('./src/components/chat/chatList/listItem.vue')['default']
    LoginCard: typeof import('./src/components/login/loginCard.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    MessageBubble: typeof import('./src/components/chat/chatPanel/messageBubble.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEl: typeof import('naive-ui')['NEl']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    PanelFooter: typeof import('./src/components/contact/contactPanel/panelFooter.vue')['default']
    RegisterCard: typeof import('./src/components/register/registerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderButton: typeof import('./src/components/contact/contactList/sliderButton.vue')['default']
  }
}
