// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatContent: typeof import('./src/components/chat/chatPanel/chatContent.vue')['default']
    ChatDisplay: typeof import('./src/components/chat/chatPanel/chatDisplay.vue')['default']
    ChatInput: typeof import('./src/components/chat/chatPanel/chatInput.vue')['default']
    ChatList: typeof import('./src/components/chat/chatList/chatList.vue')['default']
    ChatPanel: typeof import('./src/components/chat/chatPanel/chatPanel.vue')['default']
    ChatRoom: typeof import('./src/components/chat/chatRoom.vue')['default']
    HomeContent: typeof import('./src/components/home/homeContent.vue')['default']
    HomeFooter: typeof import('./src/components/home/homeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/home/homeHeader.vue')['default']
    ListItem: typeof import('./src/components/chat/chatList/listItem.vue')['default']
    LoginCard: typeof import('./src/components/login/loginCard.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEl: typeof import('naive-ui')['NEl']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RegisterCard: typeof import('./src/components/register/registerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/main/settings.vue')['default']
    SideBar: typeof import('./src/components/chat/sideBar.vue')['default']
    SideBarItem: typeof import('./src/components/chat/sideBarItem.vue')['default']
    UserInfo: typeof import('./src/components/main/userInfo.vue')['default']
    UserList: typeof import('./src/components/chat/chatList/userList.vue')['default']
    UserPanel: typeof import('./src/components/chat/chatList/userPanel.vue')['default']
  }
}
